version: '3'

services:
  postgres:
    restart: always
    image: postgres
    container_name: react_lib_db
  web:
    container_name: react_lib_web
    build: ./reactlibapp
    env_file:
      - .env
    volumes:
      - ./reactlibapp:/app
      - /app/client/node_modules/
    ports: 
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - postgres
