# link to documentation https://circleci.com/docs/2.0/language-python/
version: 2
jobs:
  build:
    working_directory: ~/Django-ReactJS-Library-App
    docker:
      - image: circleci/python:3.6.2
      - image: circleci/postgres:9.6.2
        environment:
          DB_USER: root
          DB_PASS: ''
          DB_SERVICE: postgres
          DB_PORT: 5432
          DB_NAME: circle_test
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r reactlibapp/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            cd reactlibapp
            coverage run --source libraryapp manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
