# link to documentation https://circleci.com/docs/2.0/language-python/
# link to deployment doc for heroku: https://circleci.com/docs/2.0/deployment_integrations/#heroku
version: 2
jobs:
  build:
    working_directory: ~/Django-ReactJS-Library-App
    docker:
      - image: circleci/python:3.6.2
      - image: circleci/postgres:9.6.2
        environment:
          DB_USER: root
          DB_PASS: ''
          DB_SERVICE: postgres
          DB_PORT: 5432
          DB_NAME: circle_test
    steps:
      - checkout
      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "reactlibapp/requirements.txt" }}
      - restore_cache:
          key: npm-{{ .Branch }}-{{ checksum "reactlibapp/client/package.json" }}
      - run:
          command: |
            curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd reactlibapp
            pip3 install -r requirements.txt
            cd client
            npm install
      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "reactlibapp/requirements.txt" }}
          paths:
            - "venv"
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "reactlibapp/client/package.json" }}
          paths:
            - "reactlibapp/client/node_modules"
      - run:
          command: |
            . venv/bin/activate
            cd reactlibapp/scripts
            chmod +x run_tests.sh
            ./run_tests.sh -csr
      - store_artifacts:
          path: test-reports/
          destination: tr1
  deploy-heroku:
    docker:
      - image: circleci/python:3.6.2
      - image: circleci/postgres:9.6.2
    working_directory: ~/Django-ReactJS-Library-App 
    steps:
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "8d:e9:3f:a3:79:c5:f4:af:bc:19:6c:3f:43:f5:72:2f"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push -f heroku master
            heroku run python reactlibapp/manage.py makemigrations --settings=reactlibapp.settings --app library-app-staging
            heroku run python reactlibapp/manage.py migrate --settings=reactlibapp.settings --app library-app-staging
            heroku restart            
 workflows:
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy-heroku:
           requires:
             - build
           filters:
             branches:
               only: master
